//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraCSharpFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class enregistrement
    {
        public long id { get; set; }
        public byte[] flux_video { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
