//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraCSharpFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class enregistrement
    {
        public long id { get; set; }
        public byte[] flux_video { get; set; }
        public byte[] thumbnail { get; set; }
        public System.DateTime date { get; set; }
    }
}
